const KeyboardScheme = [
    {code: 8, name: 'Back space'},
    {code: 9, name: 'Tab'},
    {code: 13, name: 'Enter'},
    {code: 16, name: 'Shift'},
    {code: 17, name: 'Left Control'},
    {code: 18, name: 'Left Alt'},
    {code: 19, name: 'Pause'},
    {code: 27, name: 'Escape'},
    {code: 32, name: 'Space'},
    {code: 37, name: 'Arrow Left'},
    {code: 38, name: 'Arrow Up'},
    {code: 39, name: 'Arrow Right'},
    {code: 40, name: 'Arrow Down'},
    {code: 45, name: 'Insert'},
    {code: 46, name: 'Delete'},
    {code: 48, name: '0'},
    {code: 49, name: '1'},
    {code: 50, name: '2'},
    {code: 51, name: '3'},
    {code: 52, name: '4'},
    {code: 53, name: '5'},
    {code: 54, name: '6'},
    {code: 55, name: '7'},
    {code: 56, name: '8'},
    {code: 57, name: '9'},
    {code: 58, name: 'Colon'},
    {code: 59, name: 'Semicolon'},
    {code: 60, name: 'Lesser than'},
    {code: 61, name: 'Equals'},
    {code: 62, name: 'Greater than'},
    {code: 63, name: 'Question mark'},
    {code: 65, name: 'A'},
    {code: 66, name: 'B'},
    {code: 67, name: 'C'},
    {code: 68, name: 'D'},
    {code: 69, name: 'E'},
    {code: 70, name: 'F'},
    {code: 71, name: 'G'},
    {code: 72, name: 'H'},
    {code: 73, name: 'I'},
    {code: 74, name: 'J'},
    {code: 75, name: 'K'},
    {code: 76, name: 'L'},
    {code: 77, name: 'M'},
    {code: 78, name: 'N'},
    {code: 79, name: 'O'},
    {code: 80, name: 'P'},
    {code: 81, name: 'Q'},
    {code: 82, name: 'R'},
    {code: 83, name: 'S'},
    {code: 84, name: 'T'},
    {code: 85, name: 'U'},
    {code: 86, name: 'V'},
    {code: 87, name: 'W'},
    {code: 88, name: 'X'},
    {code: 89, name: 'Y'},
    {code: 90, name: 'Z'},
    {code: 91, name: 'Windows'},
    {code: 96, name: "NUMPAD0"},
    {code: 97, name: "NUMPAD1"},
    {code: 98, name: "NUMPAD2"},
    {code: 99, name: "NUMPAD3"},
    {code: 100, name: "NUMPAD4"},
    {code: 101, name: "NUMPAD5"},
    {code: 102, name: "NUMPAD6"},
    {code: 103, name: "NUMPAD7"},
    {code: 104, name: "NUMPAD8"},
    {code: 105, name: "NUMPAD9"},
];

const ActionNames = {
    moveUp: 'moveup',
    moveDown: 'movedown',
    moveLeft: 'moveleft',
    moveRight: 'moveright',
    shoot: 'shoot',
    pause: 'pause',
    showKeySettings: 'showkeysettings',
    showMenu: 'showmenu'
};
const GameKeyCodes = [
    {name: ActionNames.moveUp, code: 38, action: 'Move up'},
    {name: ActionNames.moveDown, code: 40, action: 'Move down'},
    {name: ActionNames.moveLeft, code: 37, action: 'Move left'},
    {name: ActionNames.moveRight, code: 39, action: 'Move right'},
    {name: ActionNames.shoot, code: 32, action: 'Pause game'},
    {name: ActionNames.pause, code: 80, action: 'Show game menu(pauses game)'},
    {name: ActionNames.showKeySettings, code: 75, action: 'Show keyboard bindings'},
    {name: ActionNames.showMenu, code: 27, action: 'Shoot'}
];

const keyEvent = 'keydown';
export {keyEvent, ActionNames, GameKeyCodes, KeyboardScheme};